### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by JakubMatejka** [gooddata/gooddata-js#253]
May I ask if you have some changelog or migration guide between major releases? I have noticed that you released version 5.0.0 a few days ago but I don't have a clue what changed and how to proceed if I decide to upgrade our app.

**Comment by zbycz** [comment]
Hi @JakubMatejka,

thanks for pointing it out. We have just updated the readme and added migration to 6.x:
see https://github.com/gooddata/gooddata-js/blob/master/CHANGELOG.md#6.0.0

The 4.x to 5.x will follow. Thanks for patience!

Kind regards,
Pavel

**Comment by koles** [comment]
Looks like we did not fix this in the reasonable time. Sorry about that. Going forward, we have been maintaining a change log but we are not going to do anything with the historical issue of 4.x to 5.x migration. Please let us know if this this is still an issue for you.
