### ISSUE TITLE
Incorrect elements returned from `getValidElements` using an absolute date filter start or ending in the middle of a bucket

### ISSUE THREAD

**Issue by Blackbaud-StewartStephens** [gooddata/gooddata-js#312]
I have a chart with a measure compared to itself 'same period last year'.  I have set an absolute date filter beginning August 25th, 2017 (most of the way through the Aug/FY2017 bucket):

![image](https://user-images.githubusercontent.com/12860297/50565831-fe5a4280-0d00-11e9-8c1e-0ed7890c833b.png)

Upon receiving the drill event, I use the `getValidElements` function to get the elements needed to preform the drill-in in my app.  This works fine except for cases where a bucket is truncated by the date range, as in the Aug/FY2017 bucket in the chart above.

Even though I pass the chart's AFM (including date filter) into `getValidElements` through `options`, the response I receive includes all elements for the un-truncated bucket.  In this example, the Aug/FY2017 bucket shows 3 elements for the normal (right, dark blue) measure.  However, the `getValidElements` call returns 28 elements for the normal measure.  28 is the number of elements that display in the bucket if I set the date filter to start August 1st, 2017.

**Comment by martinmosko** [comment]
Closing as the issue has been added to our internal system
