### ISSUE TITLE
`convertRelativeDateFilter` function removes the date filter if there is no `to` or `from` properties

### ISSUE THREAD

**Issue by Blackbaud-MikitaYankouski** [gooddata/gooddata-js#356]
The function checks for the presence of `from` and `to` properties on the `relativeDateFilter`, and returns `null` if the properties aren't present which nulls the filter property on the insight. This is wrong since there is in fact a date filter on the insight. This results in an insight unaffected by date filter changes on our end.

The problem is either with nulling the filter if those properties aren't present, or there is an issue with the response inside of the `fetchVisualizationObject` function which retrieves the afm data in the first place.

**Comment by martinmosko** [comment]
Hi Mikita,
I'm going to find a right person for you which will help you to figure out what is going on and how to fix it.

**Comment by martinmosko** [comment]
Closing as the issue has been added to our internal system
